spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/cab_booking
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security
jwt.secret=Zm9vYmFyYmF6YmF0emZvb2JhcmJhemJhdHpmb29iYXJiYXpiYXR6Zm9vYmFyYmF6YmF0eg==
jwt.expiration=86400000

# Stripe
stripe.api.key=YOUR_STRIPE_SECRET_KEY

# WebSocket
# spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.cabbooking=DEBUG
